import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pinata Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <img
            src="https://peach-immediate-rhinoceros-66.mypinata.cloud/ipfs/QmYJCzDEsMW9iNCcU73oX2u1BXWAzZngsZC57DcndDpJ8a"
            alt="avatar"
          />
        </div>
      </main>
    </>
  );
}
